server:
  port: 8080
  host: localhost
spring: 
  main:
    allow-bean-definition-overriding: true   
  data:
    jpa:
      repositories:
        enabled: true       
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/url_shortener?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1W2w1s500.